# config.yaml
sources:
  # - sources/ital_wght_BNCE_IRGL_TRAK--prepped/shantell--light.ufo
  # - sources/ital_wght_BNCE_IRGL_TRAK--prepped/shantell--extrabold.ufo
  # - sources/ital_wght_BNCE_IRGL_TRAK--prepped/ShantellSans.designspace
  - sources/shantell-300_800.designspace
axisOrder:
  - wght
familyName: "Shantell Sans"
instances:
  shantell-300_800[wght].ttf:
    - familyName: "Shantell Sans"
      styleName: "Light"
      coordinates:
        wght: 300
outputDir: "./fonts/builder"
buildOTF: false
buildTTF: false
stat:
  shantell-300_800[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800